CREATE TABLE IF NOT EXISTS statements (
    statement_key VARCHAR(255) PRIMARY KEY,
    notified BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_statements_notified ON statements(notified);

